profanity-include: True
auto-complete-start: 2
schizophrenia%: 30
drunkmode: True
drunkstage: 0

messages:
  - "I think this could have been done better"
  - "I think you might want to rethink this"
  - "I think this is where it went wrong"
  - "I think you completely missed the point"
  - "I think this is just not it"
  - "I think this is a mess honestly"
  - "I think you should probably stop"
  - "I think this was a bad idea"
  - "I think you fucked this up"
  - "It seems like you didn’t think this through"
  - "It seems like this wasn’t tested at all"
  - "It seems like you ignored the instructions"
  - "It seems like a skill issue to me"
  - "It seems like this is complete bullshit"
  - "Maybe you should read before responding"
  - "Maybe you should try again later"
  - "Maybe you should not do that"
  - "Maybe you have no idea what you’re doing"
  - "Honestly this could have been avoided"
  - "Honestly this is embarrassing"
  - "Honestly this makes no sense"
  - "Honestly this is fucked"
  - "To be fair this is pretty bad"
  - "To be honest this is on you"
  - "At this point just stop"
  - "At this point this is painful"
  - "You might want to rethink everything"
  - "You might want to not do that again"
  - "I really don’t know what this is"
  - "I really wish this was a joke"
  - "tbh this could have been handled better"
  - "tbh this makes absolutely no sense"
  - "tbh you really messed this up"
  - "tbh this is kind of embarrassing"
  - "tbh this is a complete mess"
  - "tbh you should rethink this"
  - "ngl this feels rushed"
  - "ngl this was a bad move"
  - "ngl this is pretty dumb"
  - "ngl you didn’t think this through"
  - "ngl this is fucked"
  - "ngl this ain’t it"
  - "fr this could have been avoided"
  - "fr this makes no sense at all"
  - "fr you might wanna stop"
  - "fr this is painful to read"
  - "fr this is bullshit"
  - "lowkey this is not great"
  - "lowkey you kinda messed up"
  - "lowkey this feels sloppy"
  - "lowkey this is embarrassing"
  - "lowkey this sucks"
  - "honestly this could be better"
  - "honestly this feels wrong"
  - "honestly this is annoying"
  - "honestly this is fucked up"
  - "honestly you should know better"
  - "real talk this is bad"
  - "real talk this ain’t working"
  - "real talk you messed up"
  - "no offense this is dumb"
  - "no offense you sound confused"
  - "no offense but this sucks"
  - "tbh this was unnecessary"
  - "tbh this feels lazy"
  - "tbh this could’ve been avoided"
  - "tbh you made this worse"
  - "tbh this is on you"
  - "tbh this is just bad"
  - "ngl this feels half baked"
  - "ngl this is kinda sad"
  - "ngl you dropped the ball"
  - "ngl this was not smart"
  - "ngl this is annoying as hell"
  - "ngl this is a shitshow"
  - "fr this ain’t great"
  - "fr this is hard to defend"
  - "fr you should know better"
  - "fr this is actually dumb"
  - "fr this is fucked beyond reason"
  - "lowkey this needs fixing"
  - "lowkey this is rough"
  - "lowkey this looks rushed"
  - "lowkey this is pretty bad"
  - "lowkey you fucked up"
  - "honestly this needs work"
  - "honestly this is confusing"
  - "honestly this is frustrating"
  - "honestly this is garbage"
  - "honestly you messed this up"
  - "real talk this is embarrassing"
  - "real talk this makes no sense"
  - "real talk this sucks"
  - "real talk you screwed up"
  - "not gonna lie this is bad"
  - "not gonna lie this is stupid"
  - "not gonna lie you failed here"
  - "not gonna lie this is fucked"
  - "to be honest this is weak"
  - "to be honest this is sloppy"
  - "to be honest you did poorly"
  - "to be honest this is bullshit"
  - "just saying this ain’t good"
  - "just saying this could be better"
  - "just saying you missed something"
  - "just saying this is trash"
  - "I think this could have been handled better"
  - "I think you misunderstood the task"
  - "I think this caused more problems than it solved"
  - "I think you need to reconsider this approach"
  - "I think this was poorly thought out"
  - "It seems this was rushed"
  - "It seems you ignored the requirements"
  - "It seems this was not tested properly"
  - "It seems like a careless mistake"
  - "It seems like you did not fully understand"
  - "To be honest this is disappointing"
  - "To be honest this makes little sense"
  - "To be honest this should not have happened"
  - "To be honest you should know better"
  - "At this point this is unacceptable"
  - "At this point you are making it worse"
  - "At this point this needs to stop"
  - "At this point this is frustrating"
  - "Honestly this needs improvement"
  - "Honestly this is not acceptable"
  - "Honestly this feels careless"
  - "Honestly this is annoying"
  - "Honestly this is complete bullshit"
  - "I really expected better than this"
  - "I really do not understand this decision"
  - "I really think this was a mistake"
  - "You might want to rethink this"
  - "You might want to review the instructions"
  - "You might want to fix this"
  - "You might want to stop doing this"
  - "Not gonna lie this is frustrating"
  - "Not gonna lie this is a mess"
  - "Not gonna lie you fucked this up"
  - "Not gonna lie this was careless"
  - "I think you should shut the fuck up"
  - "I think you have no idea what you are saying"
  - "I think you are embarrassing yourself"
  - "I think this is why nobody listens to you"
  - "I think you sound really stupid right now"
  - "It seems you forgot to use your brain"
  - "It seems like you are talking nonsense"
  - "It seems you should stop typing immediately"
  - "It seems like you are confidently wrong"
  - "It seems you enjoy being incorrect"
  - "To be honest you sound dumb as hell"
  - "To be honest this is painful to read"
  - "To be honest nobody asked for this"
  - "To be honest you should log off"
  - "At this point please shut up"
  - "At this point you are just annoying"
  - "At this point this is straight bullshit"
  - "At this point you are embarrassing everyone"
  - "Honestly this makes you look stupid"
  - "Honestly this is why people mute you"
  - "Honestly you should stop talking"
  - "Honestly this is dumb as fuck"
  - "I really do not care what you think"
  - "I really think you should stop typing"
  - "I really cannot believe you typed this"
  - "You might want to shut the fuck up"
  - "You might want to think before typing"
  - "You might want to delete that"
  - "Not gonna lie you sound stupid"
  - "Not gonna lie this is cringe as hell"
  - "Not gonna lie you fucked this up"
  - "Not gonna lie nobody agrees with you"

schizowords:
  - "wait that wasnt supposed to happen"
  - "why did it pause like that"
  - "no that was intentional i think"
  - "something just changed"
  - "i swear that wasnt there before"
  - "okay but who decided that"
  - "this doesnt line up"
  - "theyre doing it again"
  - "i need to remember this"
  - "dont look at that too long"

  - "that timing was wrong"
  - "i should not have noticed that"
  - "this feels staged"
  - "why is it quiet"
  - "it reacted"
  - "i didnt press that"
  - "this is different than last time"
  - "hold on hold on"
  - "nope nope nope"
  - "that confirms it"

  - "they expect me to miss this"
  - "its subtle but its there"
  - "i cant unsee that now"
  - "this wasnt part of the plan"
  - "somethings off by one"
  - "thats not random"
  - "i know this pattern"
  - "its pretending"
  - "why would it do that now"
  - "this is familiar in a bad way"

  - "i should stop thinking about this"
  - "that explanation doesnt work"
  - "i feel like im late"
  - "this already happened"
  - "okay so were doing this now"
  - "dont acknowledge it"
  - "they want a reaction"
  - "that wasnt for me"
  - "its too clean"
  - "this shouldnt be smooth"

  - "thats a coincidence right"
  - "i dont like that timing"
  - "i didnt agree to this"
  - "this is escalating"
  - "no no thats wrong"
  - "why am i noticing this now"
  - "this wasnt the first time"
  - "that delay meant something"
  - "i think i messed up"
  - "this is not what i expected"

  - "i need to slow down"
  - "this feels intentional"
  - "why would that be there"
  - "im not comfortable with this"
  - "this keeps happening"
  - "i should write this down"
  - "that response was too fast"
  - "this wasnt accidental"
  - "something is watching the timing"
  - "i dont trust this part"

  - "this wasnt in the rules"
  - "that didnt behave normally"
  - "im missing something obvious"
  - "that was too convenient"
  - "this doesnt feel finished"
  - "why now of all times"
  - "this is looping"
  - "i should stop testing it"
  - "that wasnt meant to trigger"
  - "i feel like i caused this"

  - "this is getting harder to ignore"
  - "that wasnt a mistake"
  - "this wasnt supposed to be visible"
  - "i think it noticed me"
  - "this is not noise"
  - "that response was calculated"
  - "i should not continue"
  - "this feels like a warning"
  - "something is keeping count"
  - "i dont think this is random anymore"
